# Production override for docker-compose.yml
# This file removes volume mounts for production deployment

version: '3.8'

services:
  frontend:
    # Remove volume mounts for production
    volumes: []
    # Use production target for frontend
    build:
      target: production
    environment:
      - NODE_ENV=production
    
  backend:
    # Remove volume mounts for production
    volumes: []
    environment:
      - NODE_ENV=production
    command: npm start
